import type { OfficeProjection, OfficeProjectedItem, OfficeProjectedTurn, OfficeRunStatus } from '../../shared/office-agent';
import type { ThreadReadResponse } from './vendor/codex-protocol/v2/ThreadReadResponse';
import type { ThreadItem } from './vendor/codex-protocol/v2/ThreadItem';
import type { ItemStartedNotification } from './vendor/codex-protocol/v2/ItemStartedNotification';
import type { AgentMessageDeltaNotification } from './vendor/codex-protocol/v2/AgentMessageDeltaNotification';
import type { TurnCompletedNotification } from './vendor/codex-protocol/v2/TurnCompletedNotification';

const MAX_TEXT = 65_536;
const MAX_TURNS = 128;
const MAX_ITEMS = 1024;
const MAX_TOTAL_TEXT = 524_288;
const TERMINAL = new Set<OfficeRunStatus>(['completed', 'interrupted', 'failed']);
const TOOL_LABELS: Record<string, string> = { office_read_text: '读取文件' };
type Notification = { method: string; params?: unknown };
function record(value: unknown): value is Record<string, unknown> { return !!value && typeof value === 'object' && !Array.isArray(value); }
function text(value: string, limit = MAX_TEXT) { return value.replace(/sk-[A-Za-z0-9_-]{20,}/g, '[已隐藏]').slice(0, limit); }
function safeDuration(value: number | null): number | undefined { return typeof value === 'number' && Number.isFinite(value) && value >= 0 ? value : undefined; }

// Intentionally omit reasoning, raw Responses items, arguments and tool output.
// The source union is generated by the actual locked official runtime.
export function projectOfficeItem(item: ThreadItem): OfficeProjectedItem | undefined {
  if (!item || typeof item.id !== 'string' || item.id.length > 200) return undefined;
  switch (item.type) {
    case 'userMessage': {
      if (!Array.isArray(item.content)) return undefined;
      const content = item.content.filter(part => part.type === 'text').map(part => part.type === 'text' ? part.text : '').join('\n');
      return { id: item.id, kind: 'message', role: 'user', text: text(content), truncated: content.length > MAX_TEXT };
    }
    case 'agentMessage':
      if (typeof item.text !== 'string') return undefined;
      return { id: item.id, kind: 'message', role: 'assistant', phase: item.phase === 'commentary' ? 'commentary' : 'final_answer',
        text: text(item.text), truncated: item.text.length > MAX_TEXT };
    case 'plan': return typeof item.text === 'string' ? { id: item.id, kind: 'plan', text: text(item.text, 8000) } : undefined;
    case 'contextCompaction': return { id: item.id, kind: 'compaction', label: '上下文已压缩' };
    case 'dynamicToolCall': return typeof item.tool === 'string' ? { id: item.id, kind: 'tool',
      label: Object.prototype.hasOwnProperty.call(TOOL_LABELS, item.tool) ? TOOL_LABELS[item.tool] : text(item.tool, 120),
      status: item.status, durationMs: safeDuration(item.durationMs) } : undefined;
    case 'mcpToolCall': return { id: item.id, kind: 'tool', label: text(item.tool, 120), status: item.status, durationMs: safeDuration(item.durationMs) };
    case 'fileChange': return { id: item.id, kind: 'tool', label: '修改文件', status: item.status };
    case 'commandExecution': return { id: item.id, kind: 'tool', label: '运行命令', status: item.status, durationMs: safeDuration(item.durationMs) };
    default: return undefined;
  }
}
export function createOfficeProjection(threadId: string, model: string): OfficeProjection {
  return { schemaVersion: 'xiaozhi.office.projection.v1', threadId, provider: 'deepseek', model,
    epoch: 1, sourceSequence: 0, needsHydration: false, hasMoreHistory: false, turns: [] };
}
export function beginOfficeConnection(state: OfficeProjection): OfficeProjection {
  return { ...structuredClone(state), epoch: state.epoch + 1, sourceSequence: 0, needsHydration: true };
}
function ensureTurn(state: OfficeProjection, id: string): OfficeProjectedTurn {
  let turn = state.turns.find(turn => turn.id === id);
  if (!turn) { turn = { id, status: 'running', items: [] }; state.turns.push(turn); }
  return turn;
}
function upsert(turn: OfficeProjectedTurn, item: OfficeProjectedItem) {
  const index = turn.items.findIndex(existing => existing.id === item.id);
  if (index < 0) turn.items.push(item); else turn.items[index] = item;
}
function bound(state: OfficeProjection) {
  if (state.turns.length > MAX_TURNS) { state.turns = state.turns.slice(-MAX_TURNS); state.hasMoreHistory = true; }
  let total = 0;
  for (const turn of [...state.turns].reverse()) {
    if (turn.items.length > MAX_ITEMS) { turn.items = turn.items.slice(-MAX_ITEMS); state.hasMoreHistory = true; }
    for (const item of [...turn.items].reverse()) if (item.text) {
      const remaining = Math.max(0, MAX_TOTAL_TEXT - total);
      if (item.text.length > remaining) { item.text = item.text.slice(0, remaining); item.truncated = true; state.hasMoreHistory = true; }
      total += item.text.length;
    }
  }
}

export function ingestOfficeNotification(state: OfficeProjection, epoch: number, sequence: number, notification: Notification): boolean {
  if (epoch !== state.epoch || !Number.isSafeInteger(sequence) || sequence <= state.sourceSequence || state.needsHydration) return false;
  if (sequence !== state.sourceSequence + 1) { state.needsHydration = true; return false; }
  state.sourceSequence = sequence;
  const params = notification.params;
  if (!record(params) || params.threadId !== state.threadId) return true;
  if (notification.method === 'turn/completed' && record(params.turn) && typeof params.turn.id === 'string') {
    const value = params as TurnCompletedNotification;
    if (value.turn.status === 'inProgress') return true;
    const turn = ensureTurn(state, value.turn.id);
    if (TERMINAL.has(turn.status)) return true;
    turn.status = value.turn.status;
    if (value.turn.error?.message) turn.error = text(value.turn.error.message, 2000);
    // Turn notifications can carry a summary rather than full items; item/completed
    // or a full history read owns canonical item text.
    bound(state); return true;
  }
  if (typeof params.turnId !== 'string') return true;
  if (notification.method === 'item/agentMessage/delta') {
    const value = params as AgentMessageDeltaNotification;
    if (typeof value.itemId !== 'string' || typeof value.delta !== 'string') return true;
    const turn = ensureTurn(state, value.turnId); if (TERMINAL.has(turn.status)) return true;
    let item = turn.items.find(item => item.id === value.itemId);
    if (!item) { item = { id: value.itemId, kind: 'message', role: 'assistant', text: '' }; turn.items.push(item); }
    const next = `${item.text || ''}${value.delta}`;
    item.text = text(next); item.truncated = !!item.truncated || next.length > MAX_TEXT;
  } else if ((notification.method === 'item/started' || notification.method === 'item/completed') && record(params.item)) {
    const value = params as ItemStartedNotification;
    if (typeof value.item.id !== 'string' || typeof value.item.type !== 'string') return true;
    const item = projectOfficeItem(value.item); if (!item) return true;
    const turn = ensureTurn(state, value.turnId);
    if (TERMINAL.has(turn.status)) return true;
    upsert(turn, item);
  } else if (notification.method === 'turn/started') {
    // turn/started uses params.turn rather than params.turnId; handled by the
    // first item notification. Never regress terminal status from late events.
  }
  bound(state); return true;
}

// A partial history must never erase the displayed history. Paging is a host duty.
export function hydrateOfficeProjection(state: OfficeProjection, epoch: number, sequence: number, response: ThreadReadResponse): boolean {
  if (epoch !== state.epoch || !Number.isSafeInteger(sequence) || sequence < state.sourceSequence) return false;
  const thread = response.thread;
  if (thread.id !== state.threadId || thread.modelProvider !== state.provider || (thread.model && thread.model !== state.model)) {
    throw new Error('Office thread/provider/model snapshot mismatch');
  }
  if (!Array.isArray(thread.turns) || thread.turns.some(turn => turn.itemsView !== 'full')) { state.needsHydration = true; return false; }
  const turns = thread.turns.map(turn => ({ id: turn.id,
    status: turn.status === 'inProgress' ? 'running' as const : turn.status,
    items: turn.items.map(projectOfficeItem).filter((item): item is OfficeProjectedItem => !!item),
    ...(turn.error?.message ? { error: text(turn.error.message, 2000) } : {}) }));
  state.turns = turns; state.sourceSequence = sequence; state.needsHydration = false; state.hasMoreHistory = false;
  bound(state); return true;
}
