import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {OmniEduStore} from '../../src/main/db';
import {createAttachmentImportService} from '../../src/main/xiaozhi-agent/attachment-import-service';
import {attachmentStartHash} from '../../src/main/xiaozhi-agent/attachment-send-state';
import {createPublicImageRuntime} from '../../src/main/xiaozhi-agent/public-image-runtime';
import {validPublicImageInput,viewedPublicImages,type PublicImageDelivery} from '../../src/shared/xiaozhi-public-images';
import {estimateFullRequest} from '../../src/main/xiaozhi-agent/native-compaction';
import {applyXiaozhiEvent} from '../../src/shared/xiaozhi-projection';
const output=process.argv[2],data=path.join(output,'data'),checks:{name:string;pass:boolean}[]=[];let store=new OmniEduStore(data);
const report:{success:boolean;checks:typeof checks;error?:string;boundary:string}={success:false,checks,boundary:'Actual Electron/SQLite/captured-file/owned image utility. Confirmation and metadata responses are boundary fixtures, not official provider or rendered UI proof.'};
const check=(name:string)=>{checks.push({name,pass:true});console.log('PASS '+name);};
const close=()=>new Promise<void>((resolve,reject)=>(store as any).db.close((error:Error|null)=>error?reject(error):resolve()));
const signal=()=>new AbortController().signal;globalThis.fetch=async()=>{throw new Error('No network in native boundary acceptance');};
try{
 await store.init();const id=(await store.createAiConversationSession({title:'公开图片边界',folderId:null})).session.id;
 const sources=path.join(output,'sources');fs.mkdirSync(sources);const image=path.join(sources,'公开图表.png');fs.copyFileSync('test-results/xiaozhi-agent/pi-public-image-preflight-LanGoJ/prompt-public-synthetic.png',image);
 const importer=createAttachmentImportService({dataRoot:data,state:store.xiaozhiState.attachments,imports:store.xiaozhiState.attachmentImports});
 const draft=await importer.importFile(id,image,signal());const selected=(await store.xiaozhiState.attachments.get(id,draft.id))!;
 const prompt='请查看公开图表',selections=[{id:draft.id,revision:draft.revision}],commandId=`xicmd_${randomUUID()}`,hash=attachmentStartHash(id,prompt,selections,[selected]);
 await store.xiaozhiState.claimCommand(commandId,id,hash);
 const admitted=await store.xiaozhiState.attachmentSends.admit({sessionId:id,commandId,prompt,hash,model:'deepseek-flash',selections,attachments:[selected]});
 const row=(await store.xiaozhiState.attachments.get(id,admitted.attachments[0].id))!,args={id:row.id,revision:row.revision,purpose:'识别公开图表中的码与图形'};
 let active=true,approved=true,asked=0;const events:PublicImageDelivery[]=[];
 const base={sessionId:id,model:'deepseek-flash',inputCapable:true,state:store.xiaozhiState.attachments,importer,current:()=>active,
  authorize:async(value:typeof row)=>{const detail=await store.getAiConversationSession(id);return !detail.session.archivedAt&&detail.messages.some(v=>v.id===value.messageId&&v.metadata.agentRunId===value.runId);},
  capabilities:async()=>({id:'deepseek-flash',name:'Flash',contextWindow:1048576,maxOutputTokens:393216,inputModalities:['text','image'] as ('text'|'image')[],observedAt:new Date().toISOString(),source:'official' as const}),
  sanitize:async(text:string)=>text,confirm:async(question:string)=>{asked++;assert(question.includes('公开资料')&&question.includes('不含学生信息')&&question.includes(args.purpose));return approved;},emit:(event:PublicImageDelivery)=>events.push({...event})};
 const call=(runtime:ReturnType<typeof createPublicImageRuntime>,value:unknown=args,sig:AbortSignal=signal())=>runtime.tools[0].execute(randomUUID(),value,sig,undefined,undefined as never);
 let accessed=0;const getter={};Object.defineProperty(getter,'id',{enumerable:true,get(){accessed++;return row.id;}});assert(!validPublicImageInput(getter));assert.equal(accessed,0);assert(!validPublicImageInput({...args,path:image}));check('Strict image parameters reject accessors and arbitrary paths without executing them');
 for(const runtime of [createPublicImageRuntime({...base,inputCapable:false}),createPublicImageRuntime({...base,capabilities:async()=>({...await base.capabilities(),source:'cache' as const})})])assert((await call(runtime)).isError);assert.equal(asked,0);check('Text/unknown or cached-only capability cannot ask for or deliver an image');
 approved=false;assert((await call(createPublicImageRuntime(base))).isError);assert.equal(events.length,0);check('Declined explicit public-purpose confirmation produces no prepared image or receipt');approved=true;
 const runtime=createPublicImageRuntime(base),result=await call(runtime);assert(!result.isError);const part=result.content.find(v=>v.type==='image')!;assert(part.type==='image'&&part.mimeType==='image/png'&&part.data.length>0);assert.equal(events.at(-1)?.state,'prepared');check('Actual existing image utility decodes and prepares captured submitted image through original Hana/Pi');
 const context={messages:[{role:'toolResult',content:[part,{type:'image',data:Buffer.from('foreign image').toString('base64'),mimeType:'image/png'}]}]};
 const projected=await runtime.filterContext(context,true,signal());assert.equal(projected.messages[0].content.filter(v=>v.type==='image').length,1);const summary=await runtime.filterContext(context,false,signal());assert(!summary.messages[0].content.some(v=>v.type==='image'));check('Current prepared image is admitted; unrelated history and summarization images remain local');
 const payload={model:'deepseek-flash',messages:[{role:'user',content:[{type:'image_url',image_url:{url:`data:${part.mimeType};base64,${part.data}`}}]}]};const batch=await runtime.payload(payload,signal());assert.equal(events.at(-1)?.state,'submitting');runtime.response(batch,{stopReason:'stop'},false);assert.equal(events.at(-1)?.state,'received');
 let turn:any={id:admitted.runId,status:'running',items:[]};for(const event of events){turn=applyXiaozhiEvent(turn,{kind:'image_delivery',image:event,sessionId:id,runId:admitted.runId,sequence:1});if(event.state==='prepared')assert(!turn.items[0].sources);}
 assert.equal(turn.items[0].status,'completed');assert.equal(turn.items[0].sources[0].title,row.name);check('Projection separates preparation/submission from actual response receipt and adds source only after response');
 const receipt=events.at(-1)!;assert.deepEqual(receipt.attachment,{id:row.id,revision:row.revision,version:row.version});assert.deepEqual(viewedPublicImages([receipt]),[receipt]);check('Actual received receipt and projection preserve exact captured attachment version');
 assert.equal(viewedPublicImages([receipt,{...receipt,callId:'repeat'}]).length,1);assert.equal(viewedPublicImages([...events]).length,1);check('Duplicate calls and prepared/submitting events cannot inflate genuine image count');
 assert.equal(viewedPublicImages([receipt,{...receipt,attachment:{...receipt.attachment!,version:'a'.repeat(64)}}]).length,2);assert.equal(viewedPublicImages([receipt,{...receipt,attachment:{...receipt.attachment!,id:`xiat_${randomUUID()}`}}]).length,2);check('Distinct images and distinct captured versions have independent identities');
 for(const state of ['prepared','submitting','failed','interrupted'] as const)assert.equal(viewedPublicImages([{...receipt,state}]).length,0);check('Waiting/prepared/failed/interrupted image receipts never count as viewed');
 const {attachment,...legacy}=receipt;assert.equal(viewedPublicImages([legacy]).length,0);assert.equal(viewedPublicImages([{...receipt,attachment:{...attachment!,version:'unknown'}}]).length,0);check('Legacy missing versions and malformed identities cannot be guessed from titles');
 let readRef=0;const malicious:any={...receipt};Object.defineProperty(malicious,'attachment',{enumerable:true,get(){readRef++;return attachment;}});assert.equal(viewedPublicImages([malicious]).length,0);assert.equal(readRef,0);check('Receipt counting does not execute foreign accessors');
 await assert.rejects(runtime.payload({messages:[{role:'user',content:[{type:'image_url',image_url:{url:'https://example.com/arbitrary.png'}}]}]},signal()),/permission_denied/);check('Final provider gate rejects arbitrary remote images outside captured authority');
 const receivedEvents=events.length;runtime.begin();const fresh=await runtime.filterContext(context,true,signal());assert(!fresh.messages[0].content.some(v=>v.type==='image'));assert.equal(events.length,receivedEvents);check('New run clears image grants without replaying a received receipt or changing native image bodies');
 const small={messages:[{role:'user',timestamp:0,content:[{type:'image',data:'a'.repeat(16),mimeType:'image/png'}]}]},large={messages:[{role:'user',timestamp:0,content:[{type:'image',data:'a'.repeat(5*1024*1024),mimeType:'image/png'}]}]};assert.equal(estimateFullRequest(small,4096),estimateFullRequest(large,4096));assert(estimateFullRequest(large,4096)<10000);check('Image context estimate uses native image tokens, independent from base64 transport size');
 const failure=createPublicImageRuntime(base),failed=await call(failure),failurePart=failed.content.find(v=>v.type==='image')!;assert(failurePart.type==='image');const failureBatch=await failure.payload({messages:[{role:'user',content:[{type:'image_url',image_url:{url:`data:${failurePart.mimeType};base64,${failurePart.data}`}}]}]},signal());failure.response(failureBatch,{stopReason:'error'},false);assert.equal(events.at(-1)?.state,'failed');check('Supplier error never creates a received image receipt');
 const stopping=createPublicImageRuntime(base),late=await call(stopping),latePart=late.content.find(v=>v.type==='image')!;assert(latePart.type==='image');const lateBatch=await stopping.payload({messages:[{role:'user',content:[{type:'image_url',image_url:{url:`data:${latePart.mimeType};base64,${latePart.data}`}}]}]},signal());active=false;stopping.response(lateBatch,{stopReason:'stop'},false);assert.equal(events.at(-1)?.state,'interrupted');await assert.rejects(stopping.filterContext(context,true,signal()),/cancelled/);active=true;check('A stopped owner cannot emit a late successful receipt or continue image delivery');
 const originalRows=await store.xiaozhiState.attachments.list(id);await close();store=new OmniEduStore(data);await store.init();assert.deepEqual(await store.xiaozhiState.attachments.list(id),originalRows);fs.unlinkSync(image);
 const restoredImporter=createAttachmentImportService({dataRoot:data,state:store.xiaozhiState.attachments,imports:store.xiaozhiState.attachmentImports});const restored=createPublicImageRuntime({...base,state:store.xiaozhiState.attachments,importer:restoredImporter});assert(!(await restored.filterContext(context,true,signal())).messages[0].content.some(v=>v.type==='image'));const priorAsked=asked;assert(!(await call(restored)).isError);assert.equal(asked,priorAsked+1);check('Cold SQLite reopening preserves capture facts; deleted source uses local copy but still requires new confirmation');
 const changed=createPublicImageRuntime({...base,state:store.xiaozhiState.attachments,importer:restoredImporter});assert(!(await call(changed)).isError);const capturedFile=path.join(data,'xiaozhi-pi','attachments',id,row.path);assert(capturedFile.startsWith(data+path.sep));fs.chmodSync(capturedFile,0o600);fs.appendFileSync(capturedFile,'changed');await assert.rejects(changed.filterContext(context,true,signal()),/attachment_changed|changed/);check('Changed captured file is rejected again at request time, after an earlier confirmation');
 report.success=true;
}catch(error){report.error=String(error instanceof Error?error.stack:error).slice(0,2000);throw error;}
finally{fs.writeFileSync(path.join(output,'report.json'),JSON.stringify(report,null,2));await close();console.log(JSON.stringify({success:report.success,checks:checks.length}));}
