import type { XiaozhiModelCapabilities } from './xiaozhi-agent';
import type { XiaozhiWebPreferences } from './xiaozhi-web';
export const XIAOZHI_SETTINGS_SCHEMA='xiaozhi.settings.v1' as const;
export type XiaozhiSettingsError='invalid_input'|'permission_denied'|'busy'|'conflict'|'configuration'|'authentication'|'transport'|'timeout'|'storage_unavailable'|'model_unavailable'|'context_limit';
export const XIAOZHI_SETTINGS_ERRORS:Record<XiaozhiSettingsError,string>={invalid_input:'设置内容无效，请重新选择。',permission_denied:'无法访问这项设置。',busy:'小智正在处理任务，请结束后再修改模型配置。',conflict:'配置已经更新，请刷新后再保存。',configuration:'本地模型配置无法读取，请检查配置。',authentication:'API 密钥未通过验证，请检查后重试。',transport:'无法连接模型服务，请检查网络后重试。',timeout:'模型服务响应超时，请重试。',storage_unavailable:'本机安全存储不可用，密钥没有保存。',model_unavailable:'官方目录中没有这个模型，请刷新后重新选择。',context_limit:'当前会话内容超出目标模型容量，请先整理上下文或选择容量更大的模型。'};
export type XiaozhiSessionModel={version:number;model:string;locked:boolean};
export type XiaozhiSettingsView={schemaVersion:typeof XIAOZHI_SETTINGS_SCHEMA;version:number;provider:'deepseek';configured:boolean;maskedApiKey:string;defaultModel:string;locked:boolean;models:XiaozhiModelCapabilities[];catalogue:'official'|'cache'|'unavailable';catalogueError?:XiaozhiSettingsError;credentialError?:'configuration'|'storage_unavailable';web?:XiaozhiWebPreferences;sessionModel?:XiaozhiSessionModel};
export type XiaozhiSettingsInput={schemaVersion:typeof XIAOZHI_SETTINGS_SCHEMA;version:number;defaultModel:string;apiKey?:string};
export type XiaozhiCredentialInput={schemaVersion:typeof XIAOZHI_SETTINGS_SCHEMA;apiKey:string};
export type XiaozhiCredentialView={schemaVersion:typeof XIAOZHI_SETTINGS_SCHEMA;provider:'deepseek';models:XiaozhiModelCapabilities[]};
export type XiaozhiSessionModelInput={schemaVersion:typeof XIAOZHI_SETTINGS_SCHEMA;sessionId:string;version:number;model:string};
export type XiaozhiSettingsResult<T>={ok:true;value:T}|{ok:false;error:XiaozhiSettingsError};
