import type {ToolDefinition} from '@earendil-works/pi-coding-agent';
import type {OmniEduStore} from '../db';
import {plainStudentInput} from '../../shared/student-context';
import type {QuestionContextSource} from '../../shared/question-context';
import {PRACTICE_REVIEW_TOOLS,PRACTICE_REVIEW_ERRORS,validPracticeReview,validPracticeDraft,validPracticeSource,type PracticeReviewDraft,type PracticeReviewInput,type PracticeReviewDecision,type PracticeReviewSummary,type PracticeReviewView,type PracticeSourceInput,type PracticeReviewResult,type PracticeReviewError} from '../../shared/practice-review';
import {createStudentContextSanitizer} from '../students/context-sanitizer';
type Options={store:OmniEduStore;isCurrent:(sessionId:string,runId:string)=>boolean;canDecide:(sessionId:string,runId:string)=>boolean;emit:(sessionId:string,runId:string,value:PracticeReviewSummary)=>void;afterWrite?:()=>Promise<void>};
export function createPracticeReviewCoordinator(options:Options){
 const waits=new Map<string,{runId:string;finish:()=>void}>();
 const failure=(e:unknown):PracticeReviewError=>{const code=(e as Error)?.message;return Object.prototype.hasOwnProperty.call(PRACTICE_REVIEW_ERRORS,code)?code as PracticeReviewError:'unavailable';};
 const publish=async(sid:string,id:string)=>{const row=(await options.store.practiceReviews.list(sid)).find(r=>r.id===id);if(!row)throw new Error('permission_denied');options.emit(sid,row.runId,row);return row;};
 return{
  async review(input:PracticeReviewInput):Promise<PracticeReviewResult<PracticeReviewView>>{if(!validPracticeReview(input))return{ok:false,error:'invalid_input'};try{return{ok:true,value:await options.store.practiceReviews.review(input.sessionId,input.id)};}catch(e){return{ok:false,error:failure(e)};}},
  async source(input:PracticeSourceInput):Promise<PracticeReviewResult<PracticeReviewView>>{if(!validPracticeSource(input))return{ok:false,error:'invalid_input'};try{return{ok:true,value:await options.store.practiceReviews.source(input.studentId,input.exerciseId)};}catch(e){return{ok:false,error:failure(e)};}},
  async decide(input:PracticeReviewDecision,lease:()=>boolean=()=>true):Promise<PracticeReviewResult<PracticeReviewSummary>>{if(!validPracticeReview(input,true))return{ok:false,error:'invalid_input'};try{const row=(await options.store.practiceReviews.list(input.sessionId)).find(r=>r.id===input.id);if(!row)throw new Error('permission_denied');const value=await options.store.practiceReviews.decide(input,()=>lease()&&options.canDecide(input.sessionId,row.runId),options.afterWrite);options.emit(input.sessionId,value.runId,value);waits.get(value.id)?.finish();return{ok:true,value};}catch(e){return{ok:false,error:failure(e)};}},
  cancel(runId:string){for(const wait of waits.values())if(wait.runId===runId)wait.finish();},
  tools(sessionId:string,runId:string,studentId:string,observed:Map<string,QuestionContextSource>):ToolDefinition[]{
   const receipt=(value:unknown,isError=false)=>({content:[{type:'text' as const,text:JSON.stringify(value)}],details:{success:!isError},isError});
   return[
    {name:PRACTICE_REVIEW_TOOLS[0],label:'请教师核对练习',description:'为当前教师选定学生，把本轮已成功 education_read_question 实读的原题和教师已核对变式组成练习。items引用实际题目N，role original/similar/variant，teacherObservation是教学观察。title/reason/subject/knowledgePoint必填。题目正文从本地读取，不能在这里改答案；改题先用education_propose_questions经教师核对并重新实读。本工具等待教师修改安排并确认或拒绝；确认保存练习与引用记录，不是学生真实作答。未选学生不可用；拒绝/停止后不自动重复。',
     parameters:{type:'object',additionalProperties:false,required:['title','reason','subject','knowledgePoint','items'],properties:{title:{type:'string',minLength:1,maxLength:160},reason:{type:'string',minLength:1,maxLength:1000},subject:{type:'string',maxLength:128},knowledgePoint:{type:'string',maxLength:128},items:{type:'array',minItems:1,maxItems:8,items:{type:'object',additionalProperties:false,required:['reference','role','teacherObservation'],properties:{reference:{type:'string',pattern:'^题目[1-9][0-9]{0,2}$'},role:{type:'string',enum:['original','similar','variant']},teacherObservation:{type:'string',maxLength:1000}}}}}},
     async execute(callId,raw,signal){const abort=signal||new AbortController().signal,current=()=>!abort.aborted&&options.isCurrent(sessionId,runId);try{
      if(!studentId)throw new Error('permission_denied');abort.throwIfAborted();if(!current())throw new Error('cancelled');
      if(!plainStudentInput(raw,['title','reason','subject','knowledgePoint','items'])||!Array.isArray(raw.items)||raw.items.some(i=>!plainStudentInput(i,['reference','role','teacherObservation'])||typeof i.reference!=='string'||!observed.has(i.reference)))throw new Error('invalid_input');
      const {items,...meta}=raw,draft:PracticeReviewDraft={...meta,items:items.map((q,i)=>({index:i,role:q.role,teacherObservation:q.teacherObservation}))} as PracticeReviewDraft;if(!validPracticeDraft(draft)||new Set(items.map(q=>q.reference)).size!==items.length)throw new Error('invalid_input');
      const pending=await options.store.practiceReviews.propose(sessionId,runId,callId,draft,items.map(q=>observed.get(q.reference)!),current);
      if(pending.state==='pending')await new Promise<void>(resolve=>{let done=false;const finish=()=>{if(done)return;done=true;waits.delete(pending.id);abort.removeEventListener('abort',finish);resolve();};waits.set(pending.id,{runId,finish});abort.addEventListener('abort',finish,{once:true});if(!current())finish();else void publish(sessionId,pending.id).catch(finish);});
      abort.throwIfAborted();if(!current())throw new Error('cancelled');const row=await publish(sessionId,pending.id),confirmed=row.state==='confirmed',final=confirmed?(await options.store.practiceReviews.review(sessionId,pending.id)).draft:draft,clean=await createStudentContextSanitizer(options.store),title=await clean(final.title);abort.throwIfAborted();if(!current())throw new Error('cancelled');
      return receipt({success:confirmed,state:row.state,count:final.items.length,title,message:confirmed?'教师已核对保存练习；请调用education_read_practice读取最终安排再报告。没有新增学生作答或成绩。':'教师已拒绝，未保存练习，不要再次自动提交。'},!confirmed);
     }catch(e){if(abort.aborted)throw new Error('cancelled');const code=failure(e);return receipt({success:false,code,message:PRACTICE_REVIEW_ERRORS[code]},true);}}},
    {name:PRACTICE_REVIEW_TOOLS[1],label:'读取已确认练习',description:'按当前教师选定学生读取最近一次教师已核对练习的实际保存版本；包括题目、答案、解析和观察。无练习返回明确空结果，不是未来成绩。不能指定其他学生或路径。',parameters:{type:'object',additionalProperties:false,properties:{}},
     async execute(_callId,raw,signal){const abort=signal||new AbortController().signal;try{if(!studentId)throw new Error('permission_denied');if(!plainStudentInput(raw,[]))throw new Error('invalid_input');abort.throwIfAborted();if(!options.isCurrent(sessionId,runId))throw new Error('cancelled');const view=await options.store.practiceReviews.latest(sessionId);abort.throwIfAborted();if(!options.isCurrent(sessionId,runId))throw new Error('cancelled');if(!view)return receipt({success:true,found:false,message:'当前学生没有已核对练习。'});const e=view.exercise!,clean=await createStudentContextSanitizer(options.store),text=await clean(JSON.stringify({success:true,found:true,title:e.title,subject:e.subject,knowledgePoint:e.knowledgePoint,items:e.items.map(({questionId:_id,...q})=>q),sourceCurrent:view.sourceCurrent,message:'这是实际已保存练习安排，不是学生已完成。'}));abort.throwIfAborted();if(!options.isCurrent(sessionId,runId))throw new Error('cancelled');if(text.length>64000)throw new Error('unavailable');return{content:[{type:'text',text}],details:{success:true}};}catch(e){if(abort.aborted)throw new Error('cancelled');const code=failure(e);return receipt({success:false,code,message:PRACTICE_REVIEW_ERRORS[code]},true);}}}
   ];
  }
 };
}
