import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import electron from 'electron';
import http from 'node:http';
import {createXiaozhiBrowserHost} from '../../src/main/xiaozhi-agent/browser-host';
import {validBrowserInput,type XiaozhiBrowserInput,type XiaozhiBrowserReceipt} from '../../src/shared/xiaozhi-browser';
import {createPublicBrowserProxy} from '../../src/main/xiaozhi-agent/browser-proxy';
import {createHash} from 'node:crypto';
import {readBrowserCapture} from '../../src/main/xiaozhi-agent/browser-capture-reader';
import {validBrowserCapture,validBrowserCaptureInput} from '../../src/shared/xiaozhi-browser-capture';
const statusFile=path.resolve(process.env.OMNI_EDU_TEST_BUILD_ROOT||'out','renderer/browser-status.html');
const output=process.argv[2],report:{success:boolean;checks:{name:string;pass:boolean}[];error?:string;boundary:string}={success:false,checks:[],boundary:'Real owned Electron browser DOM/views/session/network policy. Synthetic public-origin protocol fixture for actions, plus real public HTTPS via checked-IP proxy. Not formal business UI/Pi/teacher acceptance.'};
const check=(name:string)=>{report.checks.push({name,pass:true});console.log('PASS '+name);};
const html=`<!doctype html><title>合成教研浏览器</title><h1>教研资料</h1><p id="result">尚未处理</p><input aria-label="检索内容" id="q"><input type="password" value="synthetic-secret"><select aria-label="学科" id="subject"><option value="math">数学</option><option value="cn">语文</option></select><button onclick="document.getElementById('result').textContent='已处理数学教研'">处理</button><a href="https://fixture.invalid/next">下一页</a><a href="http://127.0.0.1/private">私网</a><div style="height:1600px">尾部资料</div>`;
let writes=0,confirmations=0,allow=true,contents:electron.WebContents|undefined;
const host=createXiaozhiBrowserHost({statusFile,root:path.join(output,'captures'),sanitize:async text=>text.replaceAll('student-private','[已脱敏]'),afterTabCreated:async(wc,partition)=>{
  contents=wc;await partition.protocol.handle('https',request=>{if(new URL(request.url).hostname!=='fixture.invalid')return electron.net.fetch(request,{bypassCustomProtocolHandlers:true});if(request.method==='POST')writes++;return new Response(html,{headers:{'content-type':'text/html; charset=utf-8'}});});
}});
const id='aisession_'+randomUUID(),other='aisession_'+randomUUID(),controller=new AbortController();
const context={signal:controller.signal,dnsMode:'system' as const,current:()=>true,confirm:async()=>{confirmations++;return allow;}};
const call=(input:XiaozhiBrowserInput,sid=id)=>host.execute(sid,input,context);
const page=(value:unknown)=>{assert(value&&typeof value==='object'&&'snapshotId' in value);return value as XiaozhiBrowserReceipt;};
const ref=(p:XiaozhiBrowserReceipt,name:string)=>{const line=p.text!.split('\n').find(line=>line.includes(name)&&/\[\d+\]/.test(line));assert(line,name);const match=line.match(/\[(\d+)\]/);assert(match);return Number(match[1]);};
const until=async(fn:()=>unknown)=>{for(let i=0;i<100;i++){const value=await fn();if(value)return value;await new Promise(r=>setTimeout(r,50));}throw new Error('Native status did not arrive');};
try{
 let got=0;const accessor=Object.defineProperty({action:'snapshot'},'text',{get(){got++;return 'x';},enumerable:true});assert(!validBrowserInput(accessor));assert.equal(got,0);assert(!validBrowserInput({action:'snapshot',url:'x'}));assert(!validBrowserInput({action:'type',ref:1}));check('Strict browser boundary rejects accessors, extra action fields and missing ref epoch');
 let p=page(await call({action:'navigate',url:'https://fixture.invalid'}));assert(p.text!.includes('教研资料'));assert(!p.text!.includes('synthetic-secret'));const wc=contents!;assert.deepEqual(await wc.executeJavaScript('({node:typeof process,ipc:typeof window.omniEdu})'),{node:'undefined',ipc:'undefined'});check('Actual native view renders fixture, original Hana snapshot has refs, password value omitted and Node/business IPC absent');
 const initial=p;await assert.rejects(call({action:'snapshot',tabId:p.tabId},other),/permission_denied/);check('Cross-conversation tab identity denied');
 allow=false;await assert.rejects(call({action:'click',ref:ref(p,'处理'),snapshotId:p.snapshotId}),/permission_denied/);assert.equal(await wc.executeJavaScript("document.getElementById('result').textContent"),'尚未处理');check('Teacher rejection produces no button effect');
 allow=true;p=page(await call({action:'click',ref:ref(p,'处理'),snapshotId:p.snapshotId}));assert(p.text!.includes('已处理数学教研'));await assert.rejects(call({action:'click',ref:ref(initial,'处理'),snapshotId:initial.snapshotId}),/attachment_changed/);check('Actual authorized DOM action changes content; stale snapshot rejected');
 p=page(await call({action:'type',ref:ref(p,'检索内容'),snapshotId:p.snapshotId,text:'数学教研'}));assert.equal(await wc.executeJavaScript("document.getElementById('q').value"),'数学教研');assert(!p.text!.includes('value="数学教研"'));check('Actual input insertion uses latest ref and values stay out of the model snapshot');
 p=page(await call({action:'select',ref:ref(p,'学科'),snapshotId:p.snapshotId,value:'cn'}));assert.equal(await wc.executeJavaScript("document.getElementById('subject').value"),'cn');check('Actual select/change action works with explicit confirmation');
 await assert.rejects(call({action:'navigate',url:'http://127.0.0.1/private'}),/permission_denied/);await assert.rejects(call({action:'navigate',url:'https://fixture.invalid?token=secret'}),/permission_denied/);check('Private URLs and credential-bearing URLs refused before load');
 await wc.executeJavaScript("fetch('https://fixture.invalid/write',{method:'POST',body:'x'}).catch(()=>{})");await new Promise(r=>setTimeout(r,200));assert.equal(writes,0);check('Background POST outside explicit action scope is blocked');
 await assert.rejects(call({action:'snapshot'}),/permission_denied/);await assert.rejects(call({action:'screenshot'}),/permission_denied/);p=page(await call({action:'navigate',url:'https://fixture.invalid'}));check('Failure cannot become DOM or screenshot source; a new navigation recovers');
 const captured=await call({action:'screenshot'});assert('capture'in captured&&validBrowserCapture(captured.capture));const capture=captured.capture!;
 const local=await readBrowserCapture(path.join(output,'captures'),id,capture);assert(local.startsWith('data:image/png;base64,'));assert(fs.readdirSync(path.join(output,'captures')).length===1);check('Actual screenshot returns a versioned local capture; fd/hash/PNG dimensions verify the exact image');
 let calls=0;const bad=Object.defineProperty({schemaVersion:'xiaozhi.browser-capture.v1',sessionId:id},'captureId',{get(){calls++;return capture.id;},enumerable:true});assert(!validBrowserCaptureInput(bad));assert.equal(calls,0);assert(!validBrowserCaptureInput({schemaVersion:'xiaozhi.browser-capture.v1',sessionId:id,captureId:'../x.png'}));check('Capture endpoint selector rejects accessors and arbitrary paths');
 await assert.rejects(readBrowserCapture(path.join(output,'captures'),other,capture),/ENOENT/);const file=path.join(output,'captures',createHash('sha256').update(id).digest('hex'),capture.id),saved=fs.readFileSync(file),changed=Buffer.from(saved);changed[changed.length-1]^=1;fs.writeFileSync(file,changed);await assert.rejects(readBrowserCapture(path.join(output,'captures'),id,capture),/changed/);fs.writeFileSync(file,saved);check('Cross-session local bytes and changed file contents cannot become the original screenshot');
 const originalCapture=wc.capturePage.bind(wc);wc.capturePage=async(...args)=>{const image=await originalCapture(...args);await wc.loadURL('https://fixture.invalid/next');return image;};
 await assert.rejects(call({action:'screenshot'}),/attachment_changed/);wc.capturePage=originalCapture;check('Navigation during actual capture refuses a mismatched URL/revision receipt');
 const cancelCapture=new AbortController();wc.capturePage=async(...args)=>{const image=await originalCapture(...args);cancelCapture.abort();return image;};
 await assert.rejects(host.execute(id,{action:'screenshot'},{...context,signal:cancelCapture.signal}),error=>error instanceof Error&&error.name==='AbortError');wc.capturePage=originalCapture;check('Cancellation during actual capture cannot publish a successful receipt');
 p=page(await call({action:'navigate',url:'https://fixture.invalid/next',newTab:true}));const tabs=await call({action:'tabs'});assert('tabs' in tabs&&tabs.tabs.length===2);await call({action:'close',tabId:p.tabId});check('Real native tabs switch and close independently');
 const stopped=new AbortController();stopped.abort();await assert.rejects(host.execute(id,{action:'snapshot'},{...context,signal:stopped.signal}),()=>true);check('Cancelled command admits no new browser operation');
 const proxy=await createPublicBrowserProxy('system');try{const status=(headers={})=>new Promise<number>((resolve,reject)=>{http.get({hostname:'127.0.0.1',port:proxy.port,path:'http://127.0.0.1/private',headers},response=>{response.resume();resolve(response.statusCode!);}).on('error',reject);});assert.equal(await status(),407);assert.equal(await status({'Proxy-Authorization':'Basic '+Buffer.from(proxy.username+':'+proxy.password).toString('base64')}),403);}finally{await proxy.close();}check('Owned proxy requires ephemeral credentials and denies unauthorized/private target');
 const actual=createXiaozhiBrowserHost({statusFile,root:path.join(output,'actual'),sanitize:async t=>t});try{
  await assert.rejects(actual.execute(id,{action:'navigate',url:'http://www.moe.gov.cn'},context),/dns_blocked/);assert.deepEqual((await actual.status(id)).tabs,[]);await assert.rejects(actual.execute(id,{action:'snapshot'},context),/dns_blocked/);
  const status=await until(()=>electron.webContents.getAllWebContents().find(wc=>wc.getURL().includes('/browser-status.html#dns_blocked'))) as electron.WebContents;
  await until(()=>status.executeJavaScript("document.querySelector('[data-state=dns_blocked]')!==null"));assert((await status.executeJavaScript('document.body.innerText')).includes('网页解析受阻'));assert.deepEqual(await status.executeJavaScript('({node:typeof process,ipc:typeof window.omniEdu})'),{node:'undefined',ipc:'undefined'});
  const window=electron.BaseWindow.getAllWindows().find(w=>w.contentView.children.some(view=>(view as electron.WebContentsView).webContents===status))!;assert(window);
  for(const [width,height] of [[1366,768],[1920,1080]]){window.setContentSize(width,height);await until(async()=>await status.executeJavaScript('innerWidth')===width);fs.writeFileSync(path.join(output,`visible-dns-failure-${width}.png`),(await status.capturePage()).toPNG());}check('Actual HTTP virtual DNS denial shows original Pro state at two sizes; failure is not source or DOM success');
  const receipt=page(await actual.execute(id,{action:'navigate',url:'https://example.com'},{...context,dnsMode:'auto'}));assert(receipt.text!.includes('Example Domain'));check('Same existing browser group switches from explicit system to auto and loads real HTTPS');const domestic=page(await actual.execute(id,{action:'navigate',url:'https://www.moe.gov.cn'},{...context,dnsMode:'auto'}));assert(domestic.text!.includes('教育'));check('Actual domestic education site renders and returns real DOM snapshot');
 }finally{await actual.dispose();}
 assert(confirmations>=4);report.success=true;
}catch(error){report.error=String(error);throw error;}finally{await host.dispose();fs.writeFileSync(path.join(output,'report.json'),JSON.stringify(report,null,2));console.log('REPORT '+output);}

