import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {OmniEduStore} from '../../src/main/db';
import {createAttachmentImportService} from '../../src/main/xiaozhi-agent/attachment-import-service';
import {createAttachmentReadTools} from '../../src/main/xiaozhi-agent/attachment-read-tools';
import {attachmentStartHash} from '../../src/main/xiaozhi-agent/attachment-send-state';
import {sanitizeOfficeDocumentText} from '../../src/main/xiaozhi-agent/office-document-tools';
import {recognizeLocalImage} from '../../src/main/xiaozhi-agent/ocr-host';
import {LOCAL_OCR_SCHEMA,validLocalOcrReceipt,validOcrDecision} from '../../src/shared/xiaozhi-ocr';
const output=process.argv[2],data=path.join(output,'data'),checks:{name:string;pass:boolean}[]=[];
const report:{success:boolean;checks:typeof checks;error?:string}={success:false,checks};let store=new OmniEduStore(data);
const check=(name:string)=>{checks.push({name,pass:true});console.log('PASS '+name);};
const close=()=>new Promise<void>((resolve,reject)=>(store as any).db.close((e:Error|null)=>e?reject(e):resolve()));
globalThis.fetch=async()=>{throw new Error('Network forbidden in real native local OCR acceptance');};
const signal=()=>new AbortController().signal;
try{
 await store.init();const id=(await store.createAiConversationSession({title:'合成本地OCR',folderId:null})).session.id;
 const sources=path.join(output,'sources');fs.mkdirSync(sources);const image=path.join(sources,'教研.png');
 fs.copyFileSync('test-results/xiaozhi-agent/pi-local-ocr-preflight-8v4Ggn/synthetic.png',image);
 const importer=createAttachmentImportService({dataRoot:data,state:store.xiaozhiState.attachments,imports:store.xiaozhiState.attachmentImports});
 const item=await importer.importFile(id,image,signal()),row=(await store.xiaozhiState.attachments.get(id,item.id))!;
 let ocr=store.xiaozhiState.attachmentOcr;assert.equal(await ocr.get(row),null);await ocr.migrate();await ocr.migrate();check('Actual production SQLite initializes the additive OCR table repeatedly without changing original attachment facts');
 let getters=0;const getter={};Object.defineProperty(getter,'ok',{enumerable:true,get(){getters++;return true;}});
 assert(!validLocalOcrReceipt(getter));assert.equal(getters,0);
 assert(!validOcrDecision({schemaVersion:'xiaozhi.attachments.v1',sessionId:id,requestId:randomUUID(),selection:{id:item.id,revision:0},ocrRevision:0,decision:'approve',text:'x',path:image}));
 check('Strict OCR decision and worker result boundaries refuse accessors, extra fields and paths');
 const pending=await ocr.begin(row);await assert.rejects(ocr.begin(row),/busy/);
 const bytes=fs.readFileSync(image),result=await recognizeLocalImage(bytes,signal());
 assert(validLocalOcrReceipt(result)&&result.text.includes('OFFICE')&&result.text.includes('731928')&&result.text.includes('37')&&result.text.includes('教师资料'));
 let review=await ocr.finish(row,pending.revision,result);assert.equal(review.status,'review');assert.equal(review.original,result.text);check('Independent frozen Windows OCR executable reads the unchanged original bilingual fixture and writes actual private review facts');
 const student='合成学生'+randomUUID().slice(0,8);await store.createStudent({realName:student,displayName:'合成别名'});
 const corrected=`课堂37分钟\n练习8道\n学生${student} 电话18012345678 邮箱edu-fixture@example.invalid`;
 await assert.rejects(ocr.decide(row,review.revision+1,'approve',corrected),/changed/);review=await ocr.decide(row,review.revision,'reject','');assert.equal(review.status,'rejected');assert.equal(review.corrected,'');
 const retry=await ocr.begin(row);assert.equal(retry.status,'processing');review=await ocr.finish(row,retry.revision,result);review=await ocr.decide(row,review.revision,'approve',corrected);
 assert.equal(review.status,'approved');assert.equal(review.original,result.text);assert.equal(review.corrected,corrected);check('Actual revision CAS rejects stale approval, preserves rejected status, retries and stores separate original/corrected text');
 const selection=[{id:row.id,revision:row.revision}],commandId=`xicmd_${randomUUID()}`,prompt='读取校正文字',hash=attachmentStartHash(id,prompt,selection,[row]);
 await store.xiaozhiState.claimCommand(commandId,id,hash);const admitted=await store.xiaozhiState.attachmentSends.admit({sessionId:id,commandId,prompt,hash,model:'deepseek-flash',selections:selection,attachments:[row]});
 const submitted=(await store.xiaozhiState.attachments.get(id,admitted.attachments[0].id))!,args={id:submitted.id,revision:submitted.revision};
 const tools=createAttachmentReadTools({sessionId:id,state:store.xiaozhiState.attachments,importer,ocr,isCurrent:()=>true,
 authorize:async value=>{const detail=await store.getAiConversationSession(id);return !detail.session.archivedAt&&detail.messages.some(v=>v.id===value.messageId&&v.metadata.agentRunId===value.runId);},sanitize:text=>sanitizeOfficeDocumentText(store,text)});
 const read=await tools[1].execute(randomUUID(),args,signal(),undefined,undefined as never),payload=JSON.parse(read.content[0].text as string);
 assert(!read.isError&&payload.teacherCorrected&&payload.text.includes('37')&&payload.text.includes('8')&&payload.text.includes('[学生姓名]'));
 assert(!JSON.stringify(read).includes(student)&&!JSON.stringify(read).includes('18012345678')&&!JSON.stringify(read).includes('edu-fixture@example.invalid')&&!JSON.stringify(read).includes('base64'));
 assert(!payload.text.includes('OFFICE'));assert(payload.citation.includes('图片未上传'));check('Real submitted message/run authority reads only corrected necessary redacted text and preserves truthful local OCR source');
 await assert.rejects(ocr.decide(submitted,review.revision,'reject',''),/changed/);check('Submitted reviewed source version remains immutable; later edits require explicit new attachment version');
 const second=await importer.importFile(id,image,signal()),secondRow=(await store.xiaozhiState.attachments.get(id,second.id))!;const orphan=await ocr.begin(secondRow);
 await close();store=new OmniEduStore(data);await store.init();ocr=store.xiaozhiState.attachmentOcr;
 const saved=await ocr.get(submitted),restored=await ocr.get(secondRow);assert.equal(saved!.status,'approved');assert.equal(saved!.corrected,corrected);assert.equal(restored!.status,'interrupted');assert(restored!.revision>orphan.revision);
 check('Actual close/reopen retains approved original/correction and converts in-flight OCR to interrupted without replay');
 const foreign=(await store.createAiConversationSession({title:'另一会话',folderId:null})).session.id;assert.equal(await ocr.get({...submitted,sessionId:foreign}),null);await assert.rejects(ocr.get({...submitted,contentSha256:'a'.repeat(64)}),/changed/);
 check('Foreign session and changed source hash cannot reuse an OCR approval');
 await assert.rejects(recognizeLocalImage(bytes,signal(),path.join(output,'absent-runtime')),/unavailable/);
 const abort=new AbortController();abort.abort();await assert.rejects(recognizeLocalImage(bytes,abort.signal));check('Missing runtime and already cancelled call fail without a fallback download or worker delivery');
 const brokenRuntime=path.resolve(output,'broken-runtime'),model=path.join(brokenRuntime,'_internal','rapidocr','models','PP-OCRv6_rec_small.onnx');
 assert(brokenRuntime.startsWith(path.resolve(output)+path.sep)&&model.startsWith(brokenRuntime+path.sep));
 fs.cpSync(path.resolve('.local-ocr/dist/omni-edu-ocr'),brokenRuntime,{recursive:true,force:false,errorOnExist:true});fs.unlinkSync(model);
 await assert.rejects(recognizeLocalImage(bytes,signal(),brokenRuntime),/ENOENT|configuration/);check('Actual independent runtime copy with a missing original recognition model refuses before spawning or downloading');
 const before=await store.xiaozhiState.attachments.get(id,submitted.id);assert.deepEqual(before,submitted);report.success=true;
}catch(error){report.error=String(error instanceof Error?error.stack:error).slice(0,2200);throw error;}
finally{fs.writeFileSync(path.join(output,'report.json'),JSON.stringify(report,null,2)+'\n');await close();console.log(JSON.stringify({success:report.success,checks:checks.length}));}
